api_platform:
  show_webby: false
  title: Cinephoria API
  version: 1.0.0
  serializer:
    hydra_prefix: true
  formats:
    jsonld: ["application/ld+json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  # patch_formats:
  #   json: ["application/merge-patch+json"]
  #   jsonapi: ["application/vnd.api+json"]
  keep_legacy_inflector: false
  use_symfony_listeners: true
