lexik_jwt_authentication:
  # invalidate the token on logout by storing it in the cache
  blocklist_token:
    enabled: true
    cache: cache.app
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 86400 # in seconds, default is 3600
  api_platform:
    # check_path: /api/staff/login_check
    # check_path: /api/login_check
    username_path: email
    password_path: security.credentials.password
  token_extractors:
    # look for a token as Authorization Header
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization

    # check token in a cookie
    cookie:
      enabled: false
      name: BEARER

    # check token in query string parameter
    query_parameter:
      enabled: false
      name: bearer

    # check token in a cookie
    split_cookie:
      enabled: false
      cookies:
        - jwt_hp
        - jwt_s
  # set_cookies:
  #   jwt:
  #     lifetime: 1
  #     samesite: lax
  #     # path: /
  #     secure: true
  #     httpOnly: false
  remove_token_from_body_when_cookies_used: true
