vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    movies:
      uri_prefix: "%uploads_images_destination%"
      upload_destination: "%kernel.project_dir%/public%uploads_images_destination%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
